name: Upload Firmware to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Upload app.bin to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22

          # Đường dẫn file BIN trong repo GitHub
          source: "app/z_build/app.bin"

          # LUÔN để dấu '/' phía cuối để scp hiểu đây là thư mục
          target: "/var/www/html/ota/"

          # Cho phép ghi đè file cũ
          overwrite: true

          # Không xử lý tar, tránh tạo folder thay vì file
          strip_components: 0
